"""Developer-English test set, v2. (category, spoken, wanted).

Split: every 3rd case (index % 3 == 2) is HOLDOUT -- never looked at while
tuning rules; its score is the one reported. Conventions are the ones in
dev_mode.HELP_TEXT.
"""

SQL = [
    ("select star from users where id equals five", "SELECT * FROM users WHERE id = 5"),
    ("select top ten star from orders order by total descending", "SELECT TOP 10 * FROM orders ORDER BY total DESC"),
    ("select count star from orders where status equals quote shipped quote", "SELECT COUNT(*) FROM orders WHERE status = 'shipped'"),
    ("update employees set salary equals salary times one point one where department equals three", "UPDATE employees SET salary = salary * 1.1 WHERE department = 3"),
    ("delete from logs where created less than getdate", "DELETE FROM logs WHERE created < GETDATE()"),
    ("insert into products open bracket name comma price close bracket values open bracket quote laptop quote comma fifty thousand close bracket", "INSERT INTO products (name, price) VALUES ('laptop', 50000)"),
    ("create table customers open bracket id int primary key comma name varchar fifty close bracket", "CREATE TABLE customers (id INT PRIMARY KEY, name VARCHAR(50))"),
    ("alter table orders add discount decimal ten comma two", "ALTER TABLE orders ADD discount DECIMAL(10, 2)"),
    ("select star from orders inner join customers on orders dot customer equals customers dot id", "SELECT * FROM orders INNER JOIN customers ON orders.customer = customers.id"),
    ("drop table if exists temp underscore results", "DROP TABLE IF EXISTS temp_results"),
    ("exec sp underscore help users", "EXEC sp_help users"),
    ("begin transaction semicolon", "BEGIN TRANSACTION;"),
    ("select name comma email from users where email like quote percent at gmail dot com quote", "SELECT name, email FROM users WHERE email LIKE '%@gmail.com'"),
    ("select star from orders where total greater than or equal to one hundred and status not equal to quote pending quote", "SELECT * FROM orders WHERE total >= 100 AND status != 'pending'"),
    ("select department comma count star from employees group by department having count star greater than five", "SELECT department, COUNT(*) FROM employees GROUP BY department HAVING COUNT(*) > 5"),
    ("select star from users where deleted is null", "SELECT * FROM users WHERE deleted IS NULL"),
    ("create index ix underscore orders underscore date on orders open bracket created close bracket", "CREATE INDEX ix_orders_date ON orders (created)"),
    ("truncate table staging", "TRUNCATE TABLE staging"),
    ("select avg open bracket price close bracket from products", "SELECT AVG(price) FROM products"),
    ("use master", "USE master"),
    ("declare at id int equals ten", "DECLARE @id INT = 10"),
    ("select star from users where id equals at id", "SELECT * FROM users WHERE id = @id"),
    ("select star into hash temp from orders", "SELECT * INTO #temp FROM orders"),
    ("select star from hash temp", "SELECT * FROM #temp"),
    ("drop table hash temp", "DROP TABLE #temp"),
    ("select star from open square bracket order close square bracket", "SELECT * FROM [order]"),
    ("alter table users add bio nvarchar max", "ALTER TABLE users ADD bio NVARCHAR(MAX)"),
    ("create table logs open bracket id int identity open bracket one comma one close bracket primary key comma message nvarchar two hundred fifty five close bracket", "CREATE TABLE logs (id INT IDENTITY(1, 1) PRIMARY KEY, message NVARCHAR(255))"),
    ("select star from orders where total between one hundred and five hundred", "SELECT * FROM orders WHERE total BETWEEN 100 AND 500"),
    ("select star from users where country in open bracket quote india quote comma quote usa quote close bracket", "SELECT * FROM users WHERE country IN ('india', 'usa')"),
    ("select o dot id comma c dot name from orders o left join customers c on o dot customer equals c dot id", "SELECT o.id, c.name FROM orders o LEFT JOIN customers c ON o.customer = c.id"),
    ("select distinct city from customers order by city ascending", "SELECT DISTINCT city FROM customers ORDER BY city ASC"),
    ("select sum open bracket total close bracket as revenue from orders", "SELECT SUM(total) AS revenue FROM orders"),
    ("select max open bracket salary close bracket from employees", "SELECT MAX(salary) FROM employees"),
    ("select min open bracket price close bracket from products where stock greater than zero", "SELECT MIN(price) FROM products WHERE stock > 0"),
    ("select star from orders where created greater than dateadd open bracket day comma minus seven comma getdate close bracket", "SELECT * FROM orders WHERE created > DATEADD(DAY, -7, GETDATE())"),
    ("select cast open bracket price as int close bracket from products", "SELECT CAST(price AS INT) FROM products"),
    ("select isnull open bracket phone comma quote none quote close bracket from users", "SELECT ISNULL(phone, 'none') FROM users"),
    ("select name comma case when age less than eighteen then quote minor quote else quote adult quote end from users", "SELECT name, CASE WHEN age < 18 THEN 'minor' ELSE 'adult' END FROM users"),
    ("update users set active equals zero where last underscore login less than quote two thousand twenty four dash zero one dash zero one quote", "UPDATE users SET active = 0 WHERE last_login < '2024-01-01'"),
    ("select star from users where name like quote a percent quote", "SELECT * FROM users WHERE name LIKE 'a%'"),
    ("select top five name from products order by price descending", "SELECT TOP 5 name FROM products ORDER BY price DESC"),
    ("commit transaction", "COMMIT TRANSACTION"),
    ("rollback", "ROLLBACK"),
    ("exec sp underscore who", "EXEC sp_who"),
    ("select at at version", "SELECT @@VERSION"),
    ("select getdate", "SELECT GETDATE()"),
    ("select newid", "SELECT NEWID()"),
    ("create view active underscore users as select star from users where active equals one", "CREATE VIEW active_users AS SELECT * FROM users WHERE active = 1"),
    ("drop view active underscore users", "DROP VIEW active_users"),
    ("alter table orders drop column notes", "ALTER TABLE orders DROP COLUMN notes"),
    ("create database shop", "CREATE DATABASE shop"),
    ("use shop", "USE shop"),
    ("select star from sys dot tables", "SELECT * FROM sys.tables"),
    ("select name from sys dot databases", "SELECT name FROM sys.databases"),
    ("delete from cart where user underscore id equals forty two", "DELETE FROM cart WHERE user_id = 42"),
    ("update products set price equals price minus ten where id equals seven", "UPDATE products SET price = price - 10 WHERE id = 7"),
    ("select star from orders where status is not null", "SELECT * FROM orders WHERE status IS NOT NULL"),
    ("select star from orders order by created descending offset ten rows fetch next ten rows only", "SELECT * FROM orders ORDER BY created DESC OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY"),
    ("select count open bracket distinct customer close bracket from orders", "SELECT COUNT(DISTINCT customer) FROM orders"),
    ("select len open bracket name close bracket from users", "SELECT LEN(name) FROM users"),
    ("select upper open bracket name close bracket from users", "SELECT UPPER(name) FROM users"),
    ("insert into logs open bracket message close bracket values open bracket quote started quote close bracket", "INSERT INTO logs (message) VALUES ('started')"),
    ("select star from users u inner join roles r on u dot role equals r dot id where r dot name equals quote admin quote", "SELECT * FROM users u INNER JOIN roles r ON u.role = r.id WHERE r.name = 'admin'"),
    ("exec sp underscore rename quote users quote comma quote customers quote", "EXEC sp_rename 'users', 'customers'"),
    ("select star from orders where id in open bracket select order from returns close bracket", "SELECT * FROM orders WHERE id IN (SELECT order FROM returns)"),
    ("alter table users add constraint uq underscore email unique open bracket email close bracket", "ALTER TABLE users ADD CONSTRAINT uq_email UNIQUE (email)"),
    ("select year open bracket created close bracket comma count star from orders group by year open bracket created close bracket", "SELECT YEAR(created), COUNT(*) FROM orders GROUP BY YEAR(created)"),
    ("set nocount on", "SET NOCOUNT ON"),
    ("print quote done quote", "PRINT 'done'"),
    ("select star from users where email equals quote sumit at example dot com quote", "SELECT * FROM users WHERE email = 'sumit@example.com'"),
    ("create procedure get underscore user at id int as select star from users where id equals at id", "CREATE PROCEDURE get_user @id INT AS SELECT * FROM users WHERE id = @id"),
    ("exec get underscore user at id equals five", "EXEC get_user @id = 5"),
    ("select star from orders where total greater than one thousand", "SELECT * FROM orders WHERE total > 1000"),
    ("select coalesce open bracket nickname comma name close bracket from users", "SELECT COALESCE(nickname, name) FROM users"),
    ("grant select on orders to reporting", "GRANT SELECT ON orders TO reporting"),
    ("select star from orders where not exists open bracket select one from refunds close bracket", "SELECT * FROM orders WHERE NOT EXISTS (SELECT 1 FROM refunds)"),
    ("select round open bracket price comma two close bracket from products", "SELECT ROUND(price, 2) FROM products"),
    ("with recent as open bracket select star from orders close bracket select star from recent", "WITH recent AS (SELECT * FROM orders) SELECT * FROM recent"),
    ("select star from users where age greater than or equal to twenty one", "SELECT * FROM users WHERE age >= 21"),
]

SHELL = [
    ("cd dot dot", "cd .."),
    ("git status", "git status"),
    ("git commit dash m quote fix login bug quote", 'git commit -m "fix login bug"'),
    ("git checkout dash b feature slash login", "git checkout -b feature/login"),
    ("npm install dash dash save dash dev typescript", "npm install --save-dev typescript"),
    ("pip install dash r requirements dot txt", "pip install -r requirements.txt"),
    ("cd c colon backslash users backslash sumit", "cd C:\\users\\sumit"),
    ("git push origin main", "git push origin main"),
    ("docker run dash it dash p eight zero eight zero colon eighty nginx", "docker run -it -p 8080:80 nginx"),
    ("get dash child item dash recurse", "Get-ChildItem -Recurse"),
    ("python main dot py", "python main.py"),
    ("ssh root at one nine two dot one six eight dot one dot ten", "ssh root@192.168.1.10"),
    ("curl http colon slash slash localhost colon three thousand slash api slash users", "curl http://localhost:3000/api/users"),
    ("ls dash la pipe grep log", "ls -la | grep log"),
    ("git log dash dash oneline dash five", "git log --oneline -5"),
    ("git add dot", "git add ."),
    ("git pull", "git pull"),
    ("git stash", "git stash"),
    ("git branch dash d old dash feature", "git branch -d old-feature"),
    ("git merge develop", "git merge develop"),
    ("git reset dash dash hard head", "git reset --hard HEAD"),
    ("git diff dash dash staged", "git diff --staged"),
    ("git clone https colon slash slash github dot com slash sumitdas76 slash talkative dot git", "git clone https://github.com/sumitdas76/talkative.git"),
    ("git rebase dash i head tilde three", "git rebase -i HEAD~3"),
    ("git tag v one point three point five", "git tag v1.3.5"),
    ("npm run build", "npm run build"),
    ("npm start", "npm start"),
    ("npm install dash dash save dash dev at types slash node", "npm install --save-dev @types/node"),
    ("npx create dash react dash app my dash app", "npx create-react-app my-app"),
    ("yarn add axios", "yarn add axios"),
    ("pip install numpy pandas", "pip install numpy pandas"),
    ("python dash m venv dot venv", "python -m venv .venv"),
    ("python dash m pytest dash v", "python -m pytest -v"),
    ("docker ps dash a", "docker ps -a"),
    ("docker build dash t my dash app dot", "docker build -t my-app ."),
    ("docker compose up dash d", "docker compose up -d"),
    ("docker stop web", "docker stop web"),
    ("docker exec dash it web bash", "docker exec -it web bash"),
    ("kubectl get pods", "kubectl get pods"),
    ("kubectl get pods dash n production", "kubectl get pods -n production"),
    ("kubectl logs web dash f", "kubectl logs web -f"),
    ("kubectl apply dash f deployment dot yaml", "kubectl apply -f deployment.yaml"),
    ("cd tilde slash projects", "cd ~/projects"),
    ("cd source slash app", "cd source/app"),
    ("mkdir logs", "mkdir logs"),
    ("rm dash rf node underscore modules", "rm -rf node_modules"),
    ("cat package dot json", "cat package.json"),
    ("echo hello greater than out dot txt", "echo hello > out.txt"),
    ("npm install and and npm start", "npm install && npm start"),
    ("dir", "dir"),
    ("get dash process", "Get-Process"),
    ("get dash process pipe sort dash object cpu", "Get-Process | Sort-Object cpu"),
    ("set dash location c colon backslash projects", "Set-Location C:\\projects"),
    ("remove dash item dash recurse dash force build", "Remove-Item -Recurse -Force build"),
    ("test dash path dot env", "Test-Path .env"),
    ("dollar env colon path", "$env:path"),
    ("winget install git dot git", "winget install git.git"),
    ("code dot", "code ."),
    ("ping google dot com", "ping google.com"),
    ("ipconfig slash all", "ipconfig /all"),
    ("netstat dash ano", "netstat -ano"),
    ("taskkill slash f slash im node dot exe", "taskkill /f /im node.exe"),
    ("ssh dash i key dot pem ubuntu at ten dot zero dot zero dot five", "ssh -i key.pem ubuntu@10.0.0.5"),
    ("scp file dot txt root at server colon slash tmp", "scp file.txt root@server:/tmp"),
    ("chmod plus x deploy dot sh", "chmod +x deploy.sh"),
    ("dotnet run", "dotnet run"),
    ("dotnet new console dash n demo", "dotnet new console -n demo"),
    ("cargo build dash dash release", "cargo build --release"),
    ("node index dot js", "node index.js"),
    ("grep dash r quote todo quote dot", 'grep -r "todo" .'),
]

CODE = [
    ("if x equals equals five colon", "if x == 5:"),
    ("for i in range open bracket ten close bracket colon", "for i in range(10):"),
    ("print open bracket quote hello world quote close bracket", 'print("hello world")'),
    ("const camel case user name equals await camel case get user open bracket id close bracket semicolon", "const userName = await getUser(id);"),
    ("return x plus y", "return x + y"),
    ("def add open bracket a comma b close bracket colon", "def add(a, b):"),
    ("x plus equals one", "x += 1"),
    ("if count not equal to zero and flag colon", "if count != 0 and flag:"),
    ("snake case max retries equals three", "max_retries = 3"),
    ("import numpy as np", "import numpy as np"),
    ("console dot log open bracket result close bracket semicolon", "console.log(result);"),
    ("items equals open square bracket close square bracket", "items = []"),
    ("const add equals open bracket a comma b close bracket arrow a plus b", "const add = (a, b) => a + b"),
    ("list dot append open bracket item close bracket", "list.append(item)"),
    ("pascal case user service dot camel case get all open bracket close bracket", "UserService.getAll()"),
    ("from datetime import datetime", "from datetime import datetime"),
    ("import os", "import os"),
    ("while i less than ten colon", "while i < 10:"),
    ("elif x greater than five colon", "elif x > 5:"),
    ("else colon", "else:"),
    ("return result", "return result"),
    ("class pascal case user service colon", "class UserService:"),
    ("def underscore underscore init underscore underscore open bracket self close bracket colon", "def __init__(self):"),
    ("self dot name equals name", "self.name = name"),
    ("data equals open curly bracket close curly bracket", "data = {}"),
    ("x equals x times two", "x = x * 2"),
    ("y equals x divided by two", "y = x / 2"),
    ("with open open bracket quote data dot txt quote close bracket as f colon", 'with open("data.txt") as f:'),
    ("try colon", "try:"),
    ("except pascal case exception as e colon", "except Exception as e:"),
    ("raise pascal case value error open bracket quote invalid quote close bracket", 'raise ValueError("invalid")'),
    ("assert x equals equals one", "assert x == 1"),
    ("let count equals zero semicolon", "let count = 0;"),
    ("count plus plus semicolon", "count++;"),
    ("if open bracket x triple equals null close bracket open curly bracket", "if (x === null) {"),
    ("close curly bracket", "}"),
    ("function add open bracket a comma b close bracket open curly bracket", "function add(a, b) {"),
    ("return a plus b semicolon", "return a + b;"),
    ("const camel case api url equals quote http colon slash slash localhost colon eight thousand quote semicolon", 'const apiUrl = "http://localhost:8000";'),
    ("import react from quote react quote semicolon", 'import react from "react";'),
    ("export default app semicolon", "export default app;"),
    ("const open curly bracket data close curly bracket equals await axios dot get open bracket url close bracket semicolon", "const { data } = await axios.get(url);"),
    ("document dot camel case get element by id open bracket quote app quote close bracket", 'document.getElementById("app")'),
    ("items dot map open bracket x arrow x times two close bracket", "items.map(x => x * 2)"),
    ("if open bracket a double ampersand b close bracket", "if (a && b)"),
    ("if open bracket a double pipe b close bracket", "if (a || b)"),
    ("public class pascal case order service", "public class OrderService"),
    ("var items equals new pascal case list open angle bracket int close angle bracket open bracket close bracket semicolon", "var items = new List<int>();"),
    ("pascal case console dot pascal case write line open bracket quote hello quote close bracket semicolon", 'Console.WriteLine("hello");'),
    ("public int camel case get total open bracket close bracket", "public int getTotal()"),
    ("public string name open curly bracket get semicolon set semicolon close curly bracket", "public string name { get; set; }"),
    ("await pascal case task dot pascal case delay open bracket one thousand close bracket semicolon", "await Task.Delay(1000);"),
    ("if open bracket x not equal to null close bracket", "if (x != null)"),
    ("x equals x minus one", "x = x - 1"),
    ("total minus equals discount", "total -= discount"),
    ("print open bracket len open bracket items close bracket close bracket", "print(len(items))"),
    ("result equals open square bracket x times two for x in items close square bracket", "result = [x * 2 for x in items]"),
    ("user open square bracket quote name quote close square bracket", 'user["name"]'),
    ("items open square bracket zero close square bracket", "items[0]"),
    ("constant case max size equals one hundred", "MAX_SIZE = 100"),
    ("async def fetch open bracket url close bracket colon", "async def fetch(url):"),
    ("lambda x colon x plus one", "lambda x: x + 1"),
    ("if not items colon", "if not items:"),
    ("for key comma value in data dot items open bracket close bracket colon", "for key, value in data.items():"),
    ("return a times b", "return a * b"),
    ("x equals open bracket a plus b close bracket times c", "x = (a + b) * c"),
    ("print open bracket f quote hello quote close bracket", 'print(f"hello")'),
    ("import json", "import json"),
    ("json dot dumps open bracket data close bracket", "json.dumps(data)"),
    ("if x greater than or equal to ten and y less than or equal to five colon", "if x >= 10 and y <= 5:"),
]

PROSE = [
    ("the API returns JSON with a two hundred status", "The API returns JSON with a 200 status."),
    ("run it on localhost colon three thousand", "Run it on localhost:3000."),
    ("we upgraded to version one point two point three", "We upgraded to version 1.2.3."),
    ("check the config dot yaml file", "Check the config.yaml file."),
    ("the bug is in app dot ts line forty two", "The bug is in app.ts line 42."),
    ("use OAuth with a JWT token", "Use OAuth with a JWT token."),
    ("push it to the main branch on GitHub", "Push it to the main branch on GitHub."),
    ("the Postgres query took five hundred milliseconds", "The Postgres query took 500 milliseconds."),
    ("email me at sumit at example dot com", "Email me at sumit@example.com."),
    ("the endpoint is slash api slash v two slash users", "The endpoint is /api/v2/users."),
    ("we use Kubernetes and Docker in production", "We use Kubernetes and Docker in production."),
    ("I think the regex is wrong, it should match the whole line", "I think the regex is wrong, it should match the whole line."),
    ("the server is at ten dot zero dot zero dot five", "The server is at 10.0.0.5."),
    ("open the readme dot md file", "Open the readme.md file."),
    ("the tests are failing on the CI pipeline", "The tests are failing on the CI pipeline."),
    ("deploy it to AWS after lunch", "Deploy it to AWS after lunch."),
    ("the React component re-renders too often", "The React component re-renders too often."),
    ("I merged the pull request this morning", "I merged the pull request this morning."),
    ("set the timeout to thirty seconds", "Set the timeout to 30 seconds."),
    ("the memory usage went up to two gigabytes", "The memory usage went up to 2 gigabytes."),
    ("we should add an index on the email column", "We should add an index on the email column."),
    ("the webhook calls slash hooks slash github", "The webhook calls /hooks/github."),
    ("please review my changes in the auth module", "Please review my changes in the auth module."),
    ("the Python script reads from data dot csv", "The Python script reads from data.csv."),
    ("SQL Server is running on port fourteen thirty three", "SQL Server is running on port 1433."),
    ("the Docker image is about three hundred megabytes", "The Docker image is about 300 megabytes."),
    ("can you check the logs for errors", "Can you check the logs for errors?"),
    ("the build broke after the last commit", "The build broke after the last commit."),
    ("I'll fix the null pointer exception tomorrow", "I'll fix the null pointer exception tomorrow."),
    ("the API key is in the dot env file", "The API key is in the .env file."),
]

CASES = ([("sql", s, w) for s, w in SQL] + [("shell", s, w) for s, w in SHELL]
         + [("code", s, w) for s, w in CODE] + [("prose", s, w) for s, w in PROSE])
TUNE = [c for i, c in enumerate(CASES) if i % 3 != 2]
HOLDOUT = [c for i, c in enumerate(CASES) if i % 3 == 2]
