""".NET / JavaScript-TypeScript / full-stack test set (2026-09-27).

(category, spoken, wanted) like corpus2. Categories: "shell" (compared
case-insensitively), "code" (exact), "prose" (must NOT be classified as
code -- scored on classification only, so no grammar requests).

TUNE groups the same command said several ways -- different developers say
"-u" as "dash u", "hyphen u" or "minus u", "{" as "open curly bracket",
"open brace" or "left curly". FINAL was written in the same sitting,
BEFORE any tuning, and must never be tuned on: its score is the honest
number.
"""

# ---------------------------------------------------------------------------
# TUNE
# ---------------------------------------------------------------------------
DOTNET_CLI = [
    ("shell", "dotnet new webapi dash n pascal case orders api", "dotnet new webapi -n OrdersApi"),
    ("shell", "dot net new webapi dash n pascal case orders api", "dotnet new webapi -n OrdersApi"),
    ("shell", "dotnet new web api hyphen n pascal case orders api", "dotnet new webapi -n OrdersApi"),
    ("shell", "dotnet new console dash o my dash app", "dotnet new console -o my-app"),
    ("shell", "dotnet new console minus o my dash app", "dotnet new console -o my-app"),
    ("shell", "dotnet build dash c release", "dotnet build -c Release"),
    ("shell", "dotnet build dash dash configuration release", "dotnet build --configuration Release"),
    ("shell", "dotnet build double dash configuration release", "dotnet build --configuration Release"),
    ("shell", "dotnet run dash dash project src slash api", "dotnet run --project src/api"),
    ("shell", "dotnet run minus minus project src forward slash api", "dotnet run --project src/api"),
    ("shell", "dotnet run hyphen hyphen project src slash api", "dotnet run --project src/api"),
    ("shell", "dotnet watch run", "dotnet watch run"),
    ("shell", "dotnet restore", "dotnet restore"),
    ("shell", "dotnet clean", "dotnet clean"),
    ("shell", "dotnet test dash dash filter quote category equals unit quote", 'dotnet test --filter "Category=Unit"'),
    ("shell", "dotnet publish dash c release dash o dot slash publish", "dotnet publish -c Release -o ./publish"),
    ("shell", "dotnet add package newtonsoft dot json", "dotnet add package Newtonsoft.Json"),
    ("shell", "dotnet add package serilog dot asp net core", "dotnet add package Serilog.AspNetCore"),
    ("shell", "dotnet add package microsoft dot entity framework core dot sql server", "dotnet add package Microsoft.EntityFrameworkCore.SqlServer"),
    ("shell", "dotnet add package microsoft dot entity framework core dot design", "dotnet add package Microsoft.EntityFrameworkCore.Design"),
    ("shell", "dotnet ef migrations add pascal case initial create", "dotnet ef migrations add InitialCreate"),
    ("shell", "dotnet ef migrations add initial create", "dotnet ef migrations add InitialCreate"),
    ("shell", "dotnet e f migrations add add user table", "dotnet ef migrations add AddUserTable"),
    ("shell", "dotnet ef database update", "dotnet ef database update"),
    ("shell", "dotnet e f database update", "dotnet ef database update"),
    ("shell", "dotnet tool install dash dash global dotnet dash ef", "dotnet tool install --global dotnet-ef"),
    ("shell", "dotnet tool install dash g dotnet dash ef", "dotnet tool install -g dotnet-ef"),
    ("shell", "dotnet sln add src slash api slash api dot csproj", "dotnet sln add src/api/api.csproj"),
    ("shell", "dotnet dash dash version", "dotnet --version"),
    ("shell", "dotnet dash dash list dash sdks", "dotnet --list-sdks"),
    # Package Manager Console (PowerShell)
    ("shell", "add dash migration initial create", "Add-Migration InitialCreate"),
    ("shell", "update dash database", "Update-Database"),
    ("shell", "install dash package newtonsoft dot json", "Install-Package Newtonsoft.Json"),
    ("shell", "dollar env colon aspnetcore underscore environment equals quote development quote", '$env:ASPNETCORE_ENVIRONMENT = "Development"'),
]

CSHARP = [
    ("code", "public class pascal case user service", "public class UserService"),
    ("code", "public class pascal case user service colon pascal case i user service", "public class UserService : IUserService"),
    ("code", "public string pascal case name open curly bracket get semicolon set semicolon close curly bracket", "public string Name { get; set; }"),
    ("code", "public string pascal case name open brace get semicolon set semicolon close brace", "public string Name { get; set; }"),
    ("code", "public string pascal case name left curly get semi colon set semi colon right curly", "public string Name { get; set; }"),
    ("code", "public string pascal case name open curly get semicolon set semicolon close curly", "public string Name { get; set; }"),
    ("code", "var user equals await underscore context dot pascal case users dot pascal case find async open bracket id close bracket semicolon", "var user = await _context.Users.FindAsync(id);"),
    ("code", "if open bracket user equals equals null close bracket return pascal case not found open bracket close bracket semicolon", "if (user == null) return NotFound();"),
    ("code", "if open paren user double equals null close paren return pascal case not found open paren close paren semicolon", "if (user == null) return NotFound();"),
    ("code", "if left paren user equals equals null right paren return pascal case not found left paren right paren semicolon", "if (user == null) return NotFound();"),
    ("code", "console dot write line open bracket quote hello world quote close bracket semicolon", 'Console.WriteLine("hello world");'),
    ("code", "builder dot pascal case services dot pascal case add scoped open angle bracket pascal case i user service comma pascal case user service close angle bracket open bracket close bracket semicolon", "builder.Services.AddScoped<IUserService, UserService>();"),
    ("code", "throw new pascal case argument null exception open bracket name of open bracket id close bracket close bracket semicolon", "throw new ArgumentNullException(nameof(id));"),
    ("code", "catch open bracket exception ex close bracket", "catch (Exception ex)"),
    ("code", "public async task open angle bracket pascal case i action result close angle bracket pascal case get user open bracket int id close bracket", "public async Task<IActionResult> GetUser(int id)"),
    ("code", "open square bracket http get open bracket quote open curly bracket id close curly bracket quote close bracket close square bracket", '[HttpGet("{id}")]'),
    ("code", "open square bracket authorize close square bracket", "[Authorize]"),
    ("code", "namespace pascal case my app dot pascal case services semicolon", "namespace MyApp.Services;"),
    ("code", "var adults equals users dot pascal case where open bracket u arrow u dot pascal case age greater than or equal to eighteen close bracket dot pascal case to list open bracket close bracket semicolon", "var adults = users.Where(u => u.Age >= 18).ToList();"),
    ("code", "var adults equals users dot pascal case where open bracket u fat arrow u dot pascal case age greater than or equal to eighteen close bracket dot pascal case to list open bracket close bracket semicolon", "var adults = users.Where(u => u.Age >= 18).ToList();"),
    ("code", "private readonly pascal case i logger open angle bracket pascal case user service close angle bracket underscore logger semicolon", "private readonly ILogger<UserService> _logger;"),
    ("code", "app dot pascal case map get open bracket quote slash api slash users quote comma open bracket close bracket arrow users close bracket semicolon", 'app.MapGet("/api/users", () => users);'),
    ("code", "string dot pascal case is null or empty open bracket name close bracket", "string.IsNullOrEmpty(name)"),
    ("code", "using var scope equals app dot pascal case services dot pascal case create scope open bracket close bracket semicolon", "using var scope = app.Services.CreateScope();"),
    ("code", "return pascal case ok open bracket users close bracket semicolon", "return Ok(users);"),
    ("code", "foreach open bracket var item in items close bracket", "foreach (var item in items)"),
    # Added after FINAL showed the gap (FINAL's own cases untouched):
    ("code", "private readonly pascal case i user repository underscore repository semicolon", "private readonly IUserRepository _repository;"),
    ("code", "private static pascal case http client underscore client semicolon", "private static HttpClient _client;"),
]

JS_CLI = [
    ("shell", "npm install react dash router dash dom", "npm install react-router-dom"),
    ("shell", "npm i react dash router dash dom", "npm i react-router-dom"),
    ("shell", "npm install react hyphen router hyphen dom", "npm install react-router-dom"),
    ("shell", "npm install dash dash save dash dev typescript", "npm install --save-dev typescript"),
    ("shell", "npm install minus minus save minus dev typescript", "npm install --save-dev typescript"),
    ("shell", "npm install hyphen hyphen save hyphen dev typescript", "npm install --save-dev typescript"),
    ("shell", "npm install double dash save dash dev typescript", "npm install --save-dev typescript"),
    ("shell", "npm i dash d typescript", "npm i -D typescript"),
    ("shell", "npm run dev", "npm run dev"),
    ("shell", "npm run build", "npm run build"),
    ("shell", "npm start", "npm start"),
    ("shell", "npm test", "npm test"),
    ("shell", "npm run test colon watch", "npm run test:watch"),
    ("shell", "npm test dash dash dash dash watch", "npm test -- --watch"),
    ("shell", "npm run lint dash dash dash dash fix", "npm run lint -- --fix"),
    ("shell", "npx create dash react dash app my dash app", "npx create-react-app my-app"),
    ("shell", "npx create dash next dash app at latest", "npx create-next-app@latest"),
    ("shell", "npm create vite at latest my dash app", "npm create vite@latest my-app"),
    ("shell", "yarn add axios", "yarn add axios"),
    ("shell", "yarn add dash d eslint", "yarn add -D eslint"),
    ("shell", "pnpm install", "pnpm install"),
    ("shell", "pnpm add zod", "pnpm add zod"),
    ("shell", "npm init dash y", "npm init -y"),
    ("shell", "node index dot js", "node index.js"),
    ("shell", "node server dot js", "node server.js"),
    ("shell", "npx prisma migrate dev dash dash name init", "npx prisma migrate dev --name init"),
    ("shell", "npx prisma generate", "npx prisma generate"),
    ("shell", "npx tsc dash dash init", "npx tsc --init"),
    ("shell", "npm uninstall lodash", "npm uninstall lodash"),
    ("shell", "npm ci", "npm ci"),
    ("shell", "npm audit fix", "npm audit fix"),
    ("shell", "npm install dash g pnpm", "npm install -g pnpm"),
    ("shell", "npx eslint dot dash dash fix", "npx eslint . --fix"),
    ("shell", "npm install at types slash node", "npm install @types/node"),
    ("shell", "npm install dash dash save dash dev at types slash react", "npm install --save-dev @types/react"),
]

JS_CODE = [
    ("code", "const open square bracket count comma camel case set count close square bracket equals camel case use state open bracket zero close bracket semicolon", "const [count, setCount] = useState(0);"),
    ("code", "const open square bracket count comma set count close square bracket equals use state open bracket zero close bracket semicolon", "const [count, setCount] = useState(0);"),
    ("code", "import pascal case react from quote react quote semicolon", 'import React from "react";'),
    ("code", "import react from quote react quote semicolon", 'import React from "react";'),
    ("code", "import open curly bracket camel case use state close curly bracket from quote react quote", 'import { useState } from "react"'),
    ("code", "import open curly bracket use state comma use effect close curly bracket from quote react quote", 'import { useState, useEffect } from "react"'),
    ("code", "export default function pascal case app open bracket close bracket open curly bracket", "export default function App() {"),
    ("code", "const res equals await fetch open bracket quote slash api slash users quote close bracket semicolon", 'const res = await fetch("/api/users");'),
    ("code", "const data equals await res dot json open bracket close bracket semicolon", "const data = await res.json();"),
    ("code", "console dot log open bracket data close bracket semicolon", "console.log(data);"),
    ("code", "console dot log open paren data close paren", "console.log(data)"),
    ("code", "console dot log left paren data right paren", "console.log(data)"),
    ("code", "console dot log open parenthesis data close parenthesis", "console.log(data)"),
    ("code", "console dot log open round bracket data close round bracket", "console.log(data)"),
    ("code", "app dot get open bracket quote slash api slash users quote comma open bracket req comma res close bracket arrow open curly bracket", 'app.get("/api/users", (req, res) => {'),
    ("code", "res dot status open bracket four oh four close bracket dot json open bracket open curly bracket error colon quote not found quote close curly bracket close bracket semicolon", 'res.status(404).json({ error: "not found" });'),
    ("code", "const user equals users dot find open bracket u arrow u dot id triple equals id close bracket semicolon", "const user = users.find(u => u.id === id);"),
    ("code", "const user equals users dot find open bracket u fat arrow u dot id equals equals equals id close bracket semicolon", "const user = users.find(u => u.id === id);"),
    ("code", "camel case use effect open bracket open bracket close bracket arrow open curly bracket close curly bracket comma open square bracket close square bracket close bracket semicolon", "useEffect(() => {}, []);"),
    ("code", "use effect open bracket open bracket close bracket arrow open curly bracket close curly bracket comma open square bracket close square bracket close bracket semicolon", "useEffect(() => {}, []);"),
    ("code", "let total equals items dot reduce open bracket open bracket sum comma x close bracket arrow sum plus x dot price comma zero close bracket semicolon", "let total = items.reduce((sum, x) => sum + x.price, 0);"),
    ("code", "document dot camel case get element by id open bracket quote app quote close bracket", 'document.getElementById("app")'),
    ("code", "module dot exports equals router semicolon", "module.exports = router;"),
    ("code", "const port equals process dot env dot constant case port or or three thousand semicolon", "const port = process.env.PORT || 3000;"),
    ("code", "camel case set timeout open bracket open bracket close bracket arrow open curly bracket close curly bracket comma one thousand close bracket", "setTimeout(() => {}, 1000)"),
    ("code", "interface pascal case user open curly bracket id colon number semicolon name colon string close curly bracket", "interface User { id: number; name: string }"),
    ("code", "type pascal case props equals open curly bracket title colon string close curly bracket", "type Props = { title: string }"),
    ("code", "type pascal case status equals quote open quote or quote closed quote semicolon", 'type Status = "open" | "closed";'),
    ("code", "type pascal case result equals pascal case user or null", "type Result = User | null"),
    ("code", "const name equals user question mark dot name question mark question mark quote guest quote semicolon", 'const name = user?.name ?? "guest";'),
    ("code", "const name equals user question mark dot name double question mark quote guest quote semicolon", 'const name = user?.name ?? "guest";'),
    ("code", "backtick hello dollar open curly bracket name close curly bracket backtick", "`hello ${name}`"),
    ("code", "const copy equals open square bracket dot dot dot items close square bracket", "const copy = [...items]"),
    ("code", "const copy equals open square bracket spread items close square bracket", "const copy = [...items]"),
    ("code", "export const handler equals async open bracket event close bracket arrow open curly bracket", "export const handler = async (event) => {"),
    ("code", "if open bracket exclamation mark user close bracket return semicolon", "if (!user) return;"),
    ("code", "if open bracket bang user close bracket return semicolon", "if (!user) return;"),
    # (Not "if open bracket not user ...": Python's `not user` is right
    # there too, so no rule can pick "!" without knowing the language.)
    ("code", "return res dot json open bracket users close bracket semicolon", "return res.json(users);"),
    ("code", "const router equals express dot pascal case router open bracket close bracket semicolon", "const router = express.Router();"),
]

FULLSTACK_CLI = [
    ("shell", "docker build dash t my dash app dot", "docker build -t my-app ."),
    ("shell", "docker run dash p eight zero eight zero colon eight zero my dash app", "docker run -p 8080:80 my-app"),
    ("shell", "docker run dash d dash p three thousand colon three thousand my dash app", "docker run -d -p 3000:3000 my-app"),
    ("shell", "docker compose up dash d", "docker compose up -d"),
    ("shell", "docker dash compose up dash dash build", "docker-compose up --build"),
    ("shell", "docker ps dash a", "docker ps -a"),
    ("shell", "docker exec dash it my dash app bash", "docker exec -it my-app bash"),
    ("shell", "docker logs dash f my dash app", "docker logs -f my-app"),
    ("shell", "kubectl apply dash f deployment dot yaml", "kubectl apply -f deployment.yaml"),
    ("shell", "kubectl get pods dash n production", "kubectl get pods -n production"),
    ("shell", "az login", "az login"),
    ("shell", "az webapp up dash dash name my dash app", "az webapp up --name my-app"),
    ("shell", "git checkout dash b feature slash login", "git checkout -b feature/login"),
    ("shell", "git switch dash c feature slash login", "git switch -c feature/login"),
    ("shell", "git push dash u origin main", "git push -u origin main"),
    ("shell", "git push hyphen u origin main", "git push -u origin main"),
    ("shell", "git push minus u origin main", "git push -u origin main"),
    ("shell", "git commit dash am quote fix build quote", 'git commit -am "fix build"'),
    ("shell", "git log dash dash oneline", "git log --oneline"),
    ("shell", "git stash pop", "git stash pop"),
    ("shell", "git rebase dash i head tilde three", "git rebase -i HEAD~3"),
    ("shell", "curl dash capital x post http colon slash slash localhost colon three thousand slash api slash users", "curl -X POST http://localhost:3000/api/users"),
    ("shell", "curl localhost colon five thousand slash health", "curl localhost:5000/health"),
    ("shell", "ssh azureuser at ten dot zero dot zero dot four", "ssh azureuser@10.0.0.4"),
    ("shell", "cd src slash components", "cd src/components"),
    ("shell", "code dot", "code ."),
]

PROSE = [
    ("prose", "can you check why the dotnet build is failing on my machine", ""),
    ("prose", "i think we should use react for the front end and dotnet for the back end", ""),
    ("prose", "the docker image is too big can we slim it down", ""),
    ("prose", "please review my pull request before lunch", ""),
    ("prose", "npm is really slow on this network today", ""),
    ("prose", "let me know when the deployment finishes", ""),
    ("prose", "export the report as a pdf and send it to the client", ""),
    ("prose", "public holidays are next week so plan the release accordingly", ""),
    ("prose", "this is going to take longer than we expected", ""),
    ("prose", "document everything we changed in the api today", ""),
    ("prose", "select the best candidate from the shortlist", ""),
    ("prose", "static pages load fine but the dashboard is slow", ""),
    ("prose", "set up a call with the frontend team tomorrow", ""),
    ("prose", "node version eighteen is going out of support soon", ""),
    ("prose", "git is complaining about a merge conflict in the readme", ""),
    ("prose", "docker desktop keeps crashing after the update", ""),
]

TUNE = DOTNET_CLI + CSHARP + JS_CLI + JS_CODE + FULLSTACK_CLI + PROSE

# ---------------------------------------------------------------------------
# FINAL -- never tune on these.
# ---------------------------------------------------------------------------
FINAL = [
    # .NET CLI
    ("shell", "dotnet new mvc dash n pascal case web store", "dotnet new mvc -n WebStore"),
    ("shell", "dotnet new classlib hyphen o pascal case shop dot core", "dotnet new classlib -o Shop.Core"),
    ("shell", "dotnet add reference dot dot slash core slash core dot csproj", "dotnet add reference ../core/core.csproj"),
    ("shell", "dotnet test dash dash no dash build", "dotnet test --no-build"),
    ("shell", "dotnet run minus c release", "dotnet run -c Release"),
    ("shell", "dotnet add package microsoft dot extensions dot logging", "dotnet add package Microsoft.Extensions.Logging"),
    ("shell", "dotnet ef migrations add add orders table", "dotnet ef migrations add AddOrdersTable"),
    ("shell", "dotnet ef migrations remove", "dotnet ef migrations remove"),
    ("shell", "dotnet watch", "dotnet watch"),
    ("shell", "dotnet new gitignore", "dotnet new gitignore"),
    ("shell", "remove dash migration", "Remove-Migration"),
    # C#
    ("code", "public interface pascal case i order service", "public interface IOrderService"),
    ("code", "public int pascal case quantity open curly bracket get semicolon set semicolon close curly bracket", "public int Quantity { get; set; }"),
    ("code", "var orders equals await underscore context dot pascal case orders dot pascal case to list async open bracket close bracket semicolon", "var orders = await _context.Orders.ToListAsync();"),
    ("code", "if open paren order double equals null close paren return pascal case bad request open paren close paren semicolon", "if (order == null) return BadRequest();"),
    ("code", "console dot write line open bracket order dot id close bracket semicolon", "Console.WriteLine(order.Id);"),
    ("code", "private readonly pascal case app db context underscore context semicolon", "private readonly AppDbContext _context;"),
    ("code", "open square bracket http post close square bracket", "[HttpPost]"),
    ("code", "var total equals orders dot pascal case sum open bracket o arrow o dot pascal case amount close bracket semicolon", "var total = orders.Sum(o => o.Amount);"),
    ("code", "catch open paren exception e close paren", "catch (Exception e)"),
    ("code", "public async task pascal case save async open bracket close bracket", "public async Task SaveAsync()"),
    ("code", "return pascal case not found open bracket close bracket semicolon", "return NotFound();"),
    ("code", "public string pascal case email left curly get semicolon set semicolon right curly", "public string Email { get; set; }"),
    # JS/TS CLI
    ("shell", "npm install express", "npm install express"),
    ("shell", "npm i dash dash save dash dev jest", "npm i --save-dev jest"),
    ("shell", "npm install minus g typescript", "npm install -g typescript"),
    ("shell", "yarn dev", "yarn dev"),
    ("shell", "pnpm run build", "pnpm run build"),
    ("shell", "npx create dash vite at latest", "npx create-vite@latest"),
    ("shell", "node app dot js", "node app.js"),
    ("shell", "npm install at tanstack slash react dash query", "npm install @tanstack/react-query"),
    ("shell", "npm run start colon dev", "npm run start:dev"),
    ("shell", "npx prisma studio", "npx prisma studio"),
    ("shell", "npm install hyphen hyphen save hyphen dev prettier", "npm install --save-dev prettier"),
    # JS/TS code
    ("code", "const open square bracket items comma camel case set items close square bracket equals camel case use state open bracket open square bracket close square bracket close bracket semicolon", "const [items, setItems] = useState([]);"),
    ("code", "import axios from quote axios quote semicolon", 'import axios from "axios";'),
    ("code", "console dot error open paren err close paren semicolon", "console.error(err);"),
    ("code", "const total equals prices dot reduce open bracket open bracket a comma b close bracket arrow a plus b comma zero close bracket semicolon", "const total = prices.reduce((a, b) => a + b, 0);"),
    ("code", "if open bracket exclamation mark token close bracket return semicolon", "if (!token) return;"),
    ("code", "res dot status open bracket five hundred close bracket dot send open bracket quote server error quote close bracket semicolon", 'res.status(500).send("server error");'),
    ("code", "const city equals user question mark dot address question mark dot city semicolon", "const city = user?.address?.city;"),
    ("code", "export default pascal case home page semicolon", "export default HomePage;"),
    ("code", "const merged equals open curly bracket dot dot dot defaults comma dot dot dot options close curly bracket semicolon", "const merged = { ...defaults, ...options };"),
    ("code", "type pascal case id equals string or number semicolon", "type Id = string | number;"),
    ("code", "const done equals todos dot filter open bracket t arrow t dot done close bracket semicolon", "const done = todos.filter(t => t.done);"),
    # Full stack
    ("shell", "docker build hyphen t api dot", "docker build -t api ."),
    ("shell", "docker run minus p five thousand colon eighty api", "docker run -p 5000:80 api"),
    ("shell", "docker compose down", "docker compose down"),
    ("shell", "docker images", "docker images"),
    ("shell", "kubectl logs dash f my dash pod", "kubectl logs -f my-pod"),
    ("shell", "git checkout minus b bugfix slash login dash error", "git checkout -b bugfix/login-error"),
    ("shell", "git push origin dash dash delete old dash branch", "git push origin --delete old-branch"),
    ("shell", "git pull dash dash rebase", "git pull --rebase"),
    ("shell", "curl http colon slash slash localhost colon eight zero eight zero slash api slash health", "curl http://localhost:8080/api/health"),
    ("shell", "az account show", "az account show"),
    # Prose
    ("prose", "let me check the logs and get back to you", ""),
    ("prose", "this api is returning stale data again", ""),
    ("prose", "export controls apply to the new region so check with legal", ""),
    ("prose", "node and npm are both out of date on the build server", ""),
    ("prose", "public preview starts next monday", ""),
    ("prose", "static analysis found three new warnings", ""),
]

CASES = TUNE + FINAL
