"""FINAL test set -- written after tuning, never used for tuning. Its
score is the number reported. Same conventions as dev_mode.HELP_TEXT."""

FINAL = [
    # SQL
    ("sql", "select star from invoices where amount greater than two thousand", "SELECT * FROM invoices WHERE amount > 2000"),
    ("sql", "select top three name from employees order by salary descending", "SELECT TOP 3 name FROM employees ORDER BY salary DESC"),
    ("sql", "update accounts set balance equals balance plus fifty where id equals nine", "UPDATE accounts SET balance = balance + 50 WHERE id = 9"),
    ("sql", "delete from sessions where expires less than getdate", "DELETE FROM sessions WHERE expires < GETDATE()"),
    ("sql", "insert into tags open bracket label close bracket values open bracket quote urgent quote close bracket", "INSERT INTO tags (label) VALUES ('urgent')"),
    ("sql", "select count star from users where active equals one", "SELECT COUNT(*) FROM users WHERE active = 1"),
    ("sql", "create table notes open bracket id int primary key comma body nvarchar max close bracket", "CREATE TABLE notes (id INT PRIMARY KEY, body NVARCHAR(MAX))"),
    ("sql", "alter table products add weight decimal eight comma three", "ALTER TABLE products ADD weight DECIMAL(8, 3)"),
    ("sql", "select p dot name comma c dot title from products p inner join categories c on p dot category equals c dot id", "SELECT p.name, c.title FROM products p INNER JOIN categories c ON p.category = c.id"),
    ("sql", "drop table if exists staging underscore orders", "DROP TABLE IF EXISTS staging_orders"),
    ("sql", "exec sp underscore columns orders", "EXEC sp_columns orders"),
    ("sql", "select star from logs where level in open bracket quote error quote comma quote fatal quote close bracket", "SELECT * FROM logs WHERE level IN ('error', 'fatal')"),
    ("sql", "select city comma avg open bracket income close bracket from people group by city", "SELECT city, AVG(income) FROM people GROUP BY city"),
    ("sql", "select star from orders where shipped is null and total greater than zero", "SELECT * FROM orders WHERE shipped IS NULL AND total > 0"),
    ("sql", "declare at count int equals zero", "DECLARE @count INT = 0"),
    ("sql", "select star from hash results where score less than or equal to fifty", "SELECT * FROM #results WHERE score <= 50"),
    ("sql", "select star from products where name like quote percent phone percent quote", "SELECT * FROM products WHERE name LIKE '%phone%'"),
    ("sql", "select distinct country from customers", "SELECT DISTINCT country FROM customers"),
    ("sql", "truncate table audit underscore log", "TRUNCATE TABLE audit_log"),
    ("sql", "create index ix underscore users underscore email on users open bracket email close bracket", "CREATE INDEX ix_users_email ON users (email)"),
    ("sql", "select max open bracket created close bracket from orders", "SELECT MAX(created) FROM orders"),
    ("sql", "begin transaction", "BEGIN TRANSACTION"),
    # Terminal / PowerShell
    ("shell", "git checkout main", "git checkout main"),
    ("shell", "git commit dash m quote update readme quote", 'git commit -m "update readme"'),
    ("shell", "git push dash u origin feature slash search", "git push -u origin feature/search"),
    ("shell", "git pull origin develop", "git pull origin develop"),
    ("shell", "git branch", "git branch"),
    ("shell", "git log dash dash oneline", "git log --oneline"),
    ("shell", "npm install express", "npm install express"),
    ("shell", "npm run test", "npm run test"),
    ("shell", "pip install requests", "pip install requests"),
    ("shell", "python app dot py", "python app.py"),
    ("shell", "docker images", "docker images"),
    ("shell", "docker run dash d dash p three thousand colon three thousand my dash api", "docker run -d -p 3000:3000 my-api"),
    ("shell", "docker logs web", "docker logs web"),
    ("shell", "kubectl get services", "kubectl get services"),
    ("shell", "cd src slash components", "cd src/components"),
    ("shell", "ls dash l", "ls -l"),
    ("shell", "cat readme dot md", "cat readme.md"),
    ("shell", "get dash service", "Get-Service"),
    ("shell", "get dash content log dot txt", "Get-Content log.txt"),
    ("shell", "stop dash process dash name node", "Stop-Process -Name node"),
    ("shell", "ping eight dot eight dot eight dot eight", "ping 8.8.8.8"),
    ("shell", "ssh admin at one nine two dot one six eight dot zero dot two", "ssh admin@192.168.0.2"),
    ("shell", "curl https colon slash slash api dot github dot com", "curl https://api.github.com"),
    ("shell", "mkdir dist", "mkdir dist"),
    ("shell", "rm dash rf dist", "rm -rf dist"),
    ("shell", "git stash pop", "git stash pop"),
    # Code
    ("code", "if y equals equals zero colon", "if y == 0:"),
    ("code", "for item in items colon", "for item in items:"),
    ("code", "print open bracket quote done quote close bracket", 'print("done")'),
    ("code", "def greet open bracket name close bracket colon", "def greet(name):"),
    ("code", "return name dot upper open bracket close bracket", "return name.upper()"),
    ("code", "total plus equals price times quantity", "total += price * quantity"),
    ("code", "snake case user count equals zero", "user_count = 0"),
    ("code", "import pandas as pd", "import pandas as pd"),
    ("code", "const camel case total price equals zero semicolon", "const totalPrice = 0;"),
    ("code", "console dot log open bracket quote hi quote close bracket semicolon", 'console.log("hi");'),
    ("code", "let names equals open square bracket close square bracket semicolon", "let names = [];"),
    ("code", "if open bracket count greater than zero close bracket open curly bracket", "if (count > 0) {"),
    ("code", "return null semicolon", "return null;"),
    ("code", "names dot push open bracket name close bracket semicolon", "names.push(name);"),
    ("code", "while open bracket i less than n close bracket open curly bracket", "while (i < n) {"),
    ("code", "else open curly bracket", "else {"),
    ("code", "x equals y plus z", "x = y + z"),
    ("code", "class pascal case payment service colon", "class PaymentService:"),
    ("code", "self dot items equals open square bracket close square bracket", "self.items = []"),
    ("code", "public void pascal case save open bracket close bracket", "public void Save()"),
    # Tech prose
    ("prose", "the login page returns a four oh four error", "The login page returns a 404 error."),
    ("prose", "run the tests before you push", "Run the tests before you push."),
    ("prose", "the frontend runs on localhost colon five thousand one hundred seventy three", "The frontend runs on localhost:5173."),
    ("prose", "we moved the database to Azure last week", "We moved the database to Azure last week."),
    ("prose", "check the package dot json file for the version", "Check the package.json file for the version."),
    ("prose", "the query now takes two hundred milliseconds", "The query now takes 200 milliseconds."),
    ("prose", "I updated the README with the new setup steps", "I updated the README with the new setup steps."),
    ("prose", "the cron job runs every fifteen minutes", "The cron job runs every 15 minutes."),
    ("prose", "please rebase your branch on main", "Please rebase your branch on main."),
    ("prose", "the Redis cache is using too much memory", "The Redis cache is using too much memory."),
]
