"""Generates the Talkative app icon.

Run from the project root:  .venv\\Scripts\\python assets\\generate_icon.py

Produces:
  - assets/icon.ico              multi-resolution .ico for PyInstaller --icon
                                  and the installer's SetupIconFile
  - sumit_speak/app_icon.py      base64 PNG + set_window_icon() helper, used
                                  to set the taskbar/title-bar icon on the
                                  app's Tk windows (Tk's own default icon is
                                  the "feather" PyInstaller/Tcl mark, not the
                                  EXE's resource icon, so windows need this
                                  set explicitly even after --icon is passed)

Re-run this after changing the design below; both output files are
generated, not hand-edited.
"""

import base64
import io
import os

from PIL import Image, ImageDraw

# Brand blue already used elsewhere (tray idle dot, settings accent color).
BLUE_LIGHT = (94, 158, 214)
BLUE_DARK = (37, 76, 110)
WHITE = (255, 255, 255, 255)

SIZE = 512
CORNER_RADIUS = int(SIZE * 0.22)  # Fluent/Win11-style squircle


def _vertical_gradient(size, top, bottom):
    w, h = size
    grad = Image.new("RGB", (1, h))
    for y in range(h):
        t = y / (h - 1)
        grad.putpixel(
            (0, y),
            tuple(int(top[i] + (bottom[i] - top[i]) * t) for i in range(3)),
        )
    return grad.resize((w, h))


def _rounded_mask(size, radius):
    mask = Image.new("L", size, 0)
    d = ImageDraw.Draw(mask)
    d.rounded_rectangle((0, 0, size[0] - 1, size[1] - 1), radius=radius, fill=255)
    return mask


def _round_line(draw, xy, fill, width):
    (x0, y0), (x1, y1) = xy
    draw.line((x0, y0, x1, y1), fill=fill, width=width)
    r = width / 2
    draw.ellipse((x0 - r, y0 - r, x0 + r, y0 + r), fill=fill)
    draw.ellipse((x1 - r, y1 - r, x1 + r, y1 + r), fill=fill)


def build_icon():
    bg = _vertical_gradient((SIZE, SIZE), BLUE_LIGHT, BLUE_DARK)
    mask = _rounded_mask((SIZE, SIZE), CORNER_RADIUS)
    icon = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    icon.paste(bg, (0, 0), mask)

    d = ImageDraw.Draw(icon)
    cx = SIZE // 2

    # Mic head (capsule).
    head_w, head_h = 132, 208
    head_top = 104
    d.rounded_rectangle(
        (cx - head_w // 2, head_top, cx + head_w // 2, head_top + head_h),
        radius=head_w // 2,
        fill=WHITE,
    )

    # Pickup bracket: a thick arc cradling the mic head from below.
    arc_r = 108
    arc_cy = head_top + head_h - 34
    d.arc(
        (cx - arc_r, arc_cy - arc_r, cx + arc_r, arc_cy + arc_r),
        start=25,
        end=155,
        fill=WHITE,
        width=24,
    )

    # Stand + base.
    stand_top = arc_cy + arc_r - 6
    stand_bottom = stand_top + 56
    _round_line(d, ((cx, stand_top), (cx, stand_bottom)), WHITE, 24)
    _round_line(d, ((cx - 66, stand_bottom), (cx + 66, stand_bottom)), WHITE, 24)

    return icon


def save_ico(icon, path):
    sizes = [16, 20, 24, 32, 40, 48, 64, 128, 256]
    icon.save(path, format="ICO", sizes=[(s, s) for s in sizes])


def save_runtime_module(icon, path):
    small = icon.resize((64, 64), Image.LANCZOS)
    buf = io.BytesIO()
    small.save(buf, format="PNG")
    b64 = base64.b64encode(buf.getvalue()).decode("ascii")

    contents = '''"""App icon for Tk windows (taskbar + title bar).

Generated by assets/generate_icon.py -- do not hand-edit. Embedded as a
base64 PNG (not a bundled asset file) so PyInstaller needs no extra
--add-data entry, matching this codebase's "no image assets" packaging
preference.
"""

_ICON_PNG_BASE64 = (
    "{b64}"
)

_photo = None  # keep a reference alive; Tk drops PhotoImages with no owner


def set_window_icon(root):
    """Set the taskbar/title-bar icon for a Tk root or Toplevel.

    Safe to call on any Tk window; failures are swallowed since a missing
    icon is cosmetic, never functional.
    """
    global _photo
    try:
        import tkinter as tk

        _photo = tk.PhotoImage(data=_ICON_PNG_BASE64)
        root.iconphoto(True, _photo)
    except Exception:
        pass
'''.format(b64=b64)

    with open(path, "w", encoding="utf-8") as f:
        f.write(contents)


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    icon = build_icon()
    save_ico(icon, os.path.join(root, "assets", "icon.ico"))
    save_runtime_module(icon, os.path.join(root, "sumit_speak", "app_icon.py"))
    # Also drop a PNG preview for quick visual review at real sizes.
    preview_sizes = [16, 32, 48, 128, 256]
    strip = Image.new("RGBA", (sum(preview_sizes) + 20, 260), (30, 30, 30, 255))
    x = 5
    for s in preview_sizes:
        thumb = icon.resize((s, s), Image.LANCZOS)
        strip.paste(thumb, (x, 260 - s - 5), thumb)
        x += s + 5
    strip.save(os.path.join(root, "assets", "icon_preview.png"))
    print("Wrote assets/icon.ico, sumit_speak/app_icon.py, assets/icon_preview.png")


if __name__ == "__main__":
    main()
